# Generated by Django 5.2.7 on 2025-10-08 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        # Just mark as applied if column already exists
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL, column already exists
            reverse_sql="SELECT 1;"
        ),
    ]
