# Generated by Django 5.2.7 on 2025-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_points',
            field=models.IntegerField(default=0),
        ),
    ]
