# Generated by Django 5.2.7 on 2025-10-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_user_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='https://i.ibb.co/FbQ7wC2Q/random-pfp.jpg', max_length=500, null=True),
        ),
    ]
