# Generated by Django 5.2.7 on 2025-10-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_postcomment_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scholarships', to=settings.AUTH_USER_MODEL),
        ),
    ]
