# Generated by Django 5.2.7 on 2025-10-13 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_alter_scholarship_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefers_images', models.BooleanField(default=True)),
                ('prefers_long_content', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('preferred_authors', models.ManyToManyField(blank=True, related_name='preferred_by_users', to=settings.AUTH_USER_MODEL)),
                ('preferred_communities', models.ManyToManyField(blank=True, related_name='preferred_by', to='test_app.community')),
                ('preferred_tags', models.ManyToManyField(blank=True, related_name='preferred_by', to='test_app.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.PositiveIntegerField(default=0, help_text='Time spent viewing in seconds')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='test_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='test_app_po_user_id_fd61e6_idx'), models.Index(fields=['post', '-viewed_at'], name='test_app_po_post_id_da557d_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community_score', models.FloatField(default=0.0)),
                ('author_similarity_score', models.FloatField(default=0.0)),
                ('tag_similarity_score', models.FloatField(default=0.0)),
                ('interaction_score', models.FloatField(default=0.0)),
                ('recency_score', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to='test_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-total_score'], name='test_app_re_user_id_0d3fcc_idx'), models.Index(fields=['-total_score'], name='test_app_re_total_s_4a1e07_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SHARE', 'Share')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='test_app.post')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='test_app_us_user_id_411524_idx'), models.Index(fields=['target_user', '-created_at'], name='test_app_us_target__759fc5_idx'), models.Index(fields=['interaction_type', '-created_at'], name='test_app_us_interac_bf2d1a_idx')],
            },
        ),
    ]
