# Generated by Django 5.2.7 on 2025-10-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_userpreference_postview_recommendationscore_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='post',
        ),
        migrations.RemoveField(
            model_name='recommendationscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_authors',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_communities',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_tags',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
        migrations.DeleteModel(
            name='RecommendationScore',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
