# Generated by Django 5.2.7 on 2025-10-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_education_workexperience_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number with country code', max_length=15),
        ),
    ]
