# Generated by Django 5.2.7 on 2025-10-15 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_alter_user_status'),
    ]

    operations = [
        # Step 1: Drop all foreign key constraints that reference the id column
        migrations.RunSQL(
            """
            ALTER TABLE test_app_user DROP CONSTRAINT IF EXISTS test_app_user_invited_by_id_d49e4097_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_user_groups DROP CONSTRAINT IF EXISTS test_app_user_groups_user_id_b5d69240_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_user_user_permissions DROP CONSTRAINT IF EXISTS test_app_user_user_p_user_id_9a3bddd9_fk_test_app_ CASCADE;
            ALTER TABLE test_app_alumniprofile DROP CONSTRAINT IF EXISTS test_app_alumniprofile_user_id_b76d9d11_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_community DROP CONSTRAINT IF EXISTS test_app_community_created_by_id_10d70883_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_community_members DROP CONSTRAINT IF EXISTS test_app_community_members_user_id_0228f4cf_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_post DROP CONSTRAINT IF EXISTS test_app_post_author_id_6cc1066d_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_scholarship DROP CONSTRAINT IF EXISTS test_app_scholarship_created_by_id_81fdf49b_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_scholarshipcontribution DROP CONSTRAINT IF EXISTS test_app_scholarship_contributor_id_6675b219_fk_test_app_ CASCADE;
            ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_tag DROP CONSTRAINT IF EXISTS test_app_tag_created_by_id_8deede4f_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_usertag DROP CONSTRAINT IF EXISTS test_app_usertag_assigned_by_id_4706fa0a_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_usertag DROP CONSTRAINT IF EXISTS test_app_usertag_user_id_de1bed39_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_postcomment DROP CONSTRAINT IF EXISTS test_app_postcomment_user_id_6c457213_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_postlike DROP CONSTRAINT IF EXISTS test_app_postlike_user_id_d7ba5678_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_education DROP CONSTRAINT IF EXISTS test_app_education_user_id_c2802397_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_workexperience DROP CONSTRAINT IF EXISTS test_app_workexperience_user_id_4eb92bd8_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_skill DROP CONSTRAINT IF EXISTS test_app_skill_user_id_3d1ace44_fk_test_app_user_id CASCADE;
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Step 2: Drop the primary key constraint
        migrations.RunSQL(
            "ALTER TABLE test_app_user DROP CONSTRAINT IF EXISTS test_app_user_pkey;",
            reverse_sql="SELECT 1;"
        ),
        
        # Step 3: Drop the id column
        migrations.RunSQL(
            "ALTER TABLE test_app_user DROP COLUMN id;",
            reverse_sql="SELECT 1;"
        ),
        
        # Step 4: Add new UUID id column with default
        migrations.RunSQL(
            "ALTER TABLE test_app_user ADD COLUMN id UUID DEFAULT gen_random_uuid() NOT NULL;",
            reverse_sql="ALTER TABLE test_app_user DROP COLUMN id;"
        ),
        
        # Step 5: Make id the primary key
        migrations.RunSQL(
            "ALTER TABLE test_app_user ADD CONSTRAINT test_app_user_pkey PRIMARY KEY (id);",
            reverse_sql="ALTER TABLE test_app_user DROP CONSTRAINT test_app_user_pkey;"
        ),
        
        # Step 6: Make roll_number nullable
        migrations.RunSQL(
            "ALTER TABLE test_app_user ALTER COLUMN roll_number DROP NOT NULL;",
            reverse_sql="ALTER TABLE test_app_user ALTER COLUMN roll_number SET NOT NULL;"
        ),
        
        # Step 7: Convert invited_by_id to UUID
        migrations.RunSQL(
            """
            ALTER TABLE test_app_user ALTER COLUMN invited_by_id TYPE UUID USING NULL;
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Step 8: Recreate foreign key constraint with UUID
        migrations.RunSQL(
            """
            ALTER TABLE test_app_user ADD CONSTRAINT test_app_user_invited_by_id_fk FOREIGN KEY (invited_by_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
