# Generated by Django 5.2.7 on 2025-10-14 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_auto_20251015_0058'),
    ]

    operations = [
        # Step 1: Drop foreign key constraints that reference test_app_user
        migrations.RunSQL(
            """
            ALTER TABLE test_app_alumniprofile DROP CONSTRAINT IF EXISTS test_app_alumniprofile_user_id_b76d9d11_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_community DROP CONSTRAINT IF EXISTS test_app_community_created_by_id_10d70883_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_community_members DROP CONSTRAINT IF EXISTS test_app_community_members_user_id_0228f4cf_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_post DROP CONSTRAINT IF EXISTS test_app_post_author_id_6cc1066d_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_scholarship DROP CONSTRAINT IF EXISTS test_app_scholarship_created_by_id_81fdf49b_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_scholarshipcontribution DROP CONSTRAINT IF EXISTS test_app_scholarship_contributor_id_6675b219_fk_test_app_user_id CASCADE;
            ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_tag DROP CONSTRAINT IF EXISTS test_app_tag_created_by_id_8deede4f_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_usertag DROP CONSTRAINT IF EXISTS test_app_usertag_assigned_by_id_4706fa0a_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_usertag DROP CONSTRAINT IF EXISTS test_app_usertag_user_id_de1bed39_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_postcomment DROP CONSTRAINT IF EXISTS test_app_postcomment_user_id_6c457213_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_postlike DROP CONSTRAINT IF EXISTS test_app_postlike_user_id_d7ba5678_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_education DROP CONSTRAINT IF EXISTS test_app_education_user_id_c2802397_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_workexperience DROP CONSTRAINT IF EXISTS test_app_workexperience_user_id_4eb92bd8_fk_test_app_user_id CASCADE;
            ALTER TABLE test_app_skill DROP CONSTRAINT IF EXISTS test_app_skill_user_id_3d1ace44_fk_test_app_user_id CASCADE;
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Step 2: Convert all foreign key columns to UUID
        migrations.RunSQL(
            """
            ALTER TABLE test_app_alumniprofile ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_community ALTER COLUMN created_by_id TYPE UUID USING created_by_id::uuid;
            ALTER TABLE test_app_community_members ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_post ALTER COLUMN author_id TYPE UUID USING author_id::uuid;
            ALTER TABLE test_app_scholarship ALTER COLUMN created_by_id TYPE UUID USING created_by_id::uuid;
            ALTER TABLE test_app_scholarshipcontribution ALTER COLUMN contributor_id TYPE UUID USING contributor_id::uuid;
            ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_tag ALTER COLUMN created_by_id TYPE UUID USING created_by_id::uuid;
            ALTER TABLE test_app_usertag ALTER COLUMN assigned_by_id TYPE UUID USING assigned_by_id::uuid;
            ALTER TABLE test_app_usertag ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_postcomment ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_postlike ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_education ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_workexperience ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            ALTER TABLE test_app_skill ALTER COLUMN user_id TYPE UUID USING user_id::uuid;
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Step 3: Recreate foreign key constraints
        migrations.RunSQL(
            """
            ALTER TABLE test_app_alumniprofile ADD CONSTRAINT test_app_alumniprofile_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_community ADD CONSTRAINT test_app_community_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_community_members ADD CONSTRAINT test_app_community_members_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_post ADD CONSTRAINT test_app_post_author_id_fk FOREIGN KEY (author_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_scholarship ADD CONSTRAINT test_app_scholarship_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_scholarshipcontribution ADD CONSTRAINT test_app_scholarship_contributor_id_fk FOREIGN KEY (contributor_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_tag ADD CONSTRAINT test_app_tag_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_usertag ADD CONSTRAINT test_app_usertag_assigned_by_id_fk FOREIGN KEY (assigned_by_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_usertag ADD CONSTRAINT test_app_usertag_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_postcomment ADD CONSTRAINT test_app_postcomment_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_postlike ADD CONSTRAINT test_app_postlike_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_education ADD CONSTRAINT test_app_education_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_workexperience ADD CONSTRAINT test_app_workexperience_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE test_app_skill ADD CONSTRAINT test_app_skill_user_id_fk FOREIGN KEY (user_id) REFERENCES test_app_user(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
