# Generated by Django 5.2.7 on 2025-10-14 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_fix_alumniprofile_user_id_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
