# Generated by Django 5.2.7 on 2025-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_add_alumniprofile_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ALUMNI', 'Alumni'), ('ASSOCIATE', 'Associate Member'), ('ADMIN', 'Admin'), ('ACCOUNTS', 'Accounts')], default='ALUMNI', max_length=10),
        ),
    ]
